# Generated by Django 3.2 on 2021-05-06 22:15

from django.db import migrations, models
import django.db.models.deletion

# For type checking
import typing
from django.db.migrations.operations.base import Operation


class Migration(migrations.Migration):

    initial: bool = True

    dependencies: typing.List[str] = [
    ]

    operations: typing.List[Operation] = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('question_text', models.CharField(max_length=240)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
            ],
        ),
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.BigAutoField(auto_created=True,
                 primary_key=True, serialize=False, verbose_name='ID')),
                ('choice_text', models.CharField(max_length=120)),
                ('votes', models.IntegerField(default=0)),
                ('question', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='polls.question')),
            ],
        ),
    ]
